merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.bands_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'), # ajouter ce motif sous notre autre motif de groupes
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change', views.band_update, name='band-change'),
    path('bands/<int:id>/delete', views.band_delete, name='band-delete'),
    path('about-us/', views.about),
    path('contact-us/', views.contact, name='contact-us'),
    path('email-sent', views.redirect_email_sent, name='email-sent'),
    path('listing/', views.listing_list, name='listing-list'),
    path('listing/add', views.listing_create, name='listing-create'),
    path('listing/<int:id>', views.listing_detail, name='listing-detail'),
    path('listing/<int:id>/delete', views.listing_delete, name='listing-delete'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    def __str__(self):
        return f"{self.name}"
    
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    name = models.fields.CharField(max_length=100)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    
class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = "RC"
        CLOTHINGS = "CL"
        POSTER = "PS"
        MISCELLANEOUS = "MS"
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=100, null=False, default='Pas de description')
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MinValueValidator(2000)], null=True)
    type = models.CharField(choices=Type.choices, max_length=20, null=False, default="Autres")
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)


class Contact(models.Model):
    name = models.fields.CharField(max_length=100)
    email = models.fields.EmailField()
    message = models.fields.CharField(max_length=1000)

merchex/listings/forms.py
# listings/forms.py

from django import forms
from listings.models import Band, Contact, Listing
    

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
# ~/projects/django-web-app/merchex/listings/views.py

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm


def bands_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/bands_list.html',
                  {'bands': bands})


def band_detail(request, id):  # notez le paramètre id supplémentaire
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request,
                  'listings/band_create.html',
                  {'form': form})


def band_update(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_delete.html',
                  {'band': band})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/band_delete.html',
                    {'band': band})

def about(request):
    return render(request,
                  'listings/about_us.html')


def redirect_email_sent(request):
    print('bonjour')
    return HttpResponse("<h1>EMAIL ENVOYE, NOUS VOUS REPONDRONS</h1>")


def contact(request):
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
             subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
             message=form.cleaned_data['message'],
             from_email=form.cleaned_data['email'],
             recipient_list=['admin@merchex.xyz'],
             )
        return redirect('email-sent')  # ajoutez cette instruction de retour
    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).
    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()
    return render(request,
                  'listings/contact_us.html',
                  {'form': form})


def listing_list(request):
    listing = Listing.objects.all()
    return render(request,
                  'listings/listings_list.html',
                  {"listing": listing})


def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request,
                  'listings/listing_detail.html',
                  {"listing": listing})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return render(request,
                  'listings/listing_create.html',
                  {'form': form})


def listing_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        if Listing.objects.filter(id=id).exists():
            listing.delete()
        return redirect('listing-list')  # Redirection vers la liste des listes après la suppression

    return render(request,
                  'listings/listing_delete.html',
                  {'article': listing})

merchex/listings/templates/listings/about_us.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>À propos</h1>
<p>Nous adorons merch !</p>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>AJOUT D'UN GROUPE</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
# listings/templates/listings/band_detail.html

{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>
<a href="{% url 'band-change' band.id %}">Mettre à jour les information du groupe</a>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 {% if band.official_homepage %}
 <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
 {% endif %}
 <li>{{ band.biography }}</li>
 {% for listing in band.listing_set.all %}
    <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title|upper }}</a></li>
 {% endfor %}
</ul>
<a href="{% url 'band-delete' band.id %}">Supprimer le groupe</a>
{% endblock %}

merchex/listings/templates/listings/band_update.html
<h1>Mise à jour du groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

merchex/listings/templates/listings/bands_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<ul>
 {% for band in bands %}
 <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
 {% endfor %}
 <a href="{% url 'band-create' %}">Ajouter un nouveau groupe</a>
</ul>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}">
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Produits</a>
            <a href="{% url 'contact-us' %}">A propos</a>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

merchex/listings/templates/listings/contact_us.html
{% extends 'listings/base.html' %}
{% block content %}
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>AJOUT D'UN ARTICLE</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Etes vous sur de vouloir supprimer l'article {{ article.title }}</h1>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>
{% endblock %}

merchex/listings/templates/listings/listing_detail.html
# listings/templates/listings/band_detail.html

{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Titre : {{ listing.title }}</li>
 <li>Description : {{ listing.description }}</li>
 <li>Vendu : {{ listing.sold|yesno }}</li>
 {% if listing.year %}
 <li>{{ listing.year }}</li>
 {% endif %}
 <li>Type : listing.type</li>
 <li>Groupe associé : listing.band</li>
 <li><a href="{% url 'band-detail' listing.id %}">Lien vers le groupe</a></li>
 <li>{{ band.biography }}</li>
</ul>
<a href="{% url 'listing-delete' listing.id %}">Supprimer cet article</a>
{% endblock %}

merchex/listings/templates/listings/listings_list.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Voici la liste:</h1>
<ul>
    {% for listing in listing %}
    <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
    {% endfor %}
</ul>
<a href="{% url 'listing-create' %}">AJOUER UN NOUVEL ARTICLE</a>
{% endblock %}